export const TEXT_NODES = {
	common: {
		// sidebar
		profileName: document.getElementById("card-name"),
		profileDescription: document.getElementById("card-description"),
		brief: document.getElementById("profile-brief"),
		profilePortfolioBtn: document.getElementById("profile-portfolio-btn"),
		profileMail: document.getElementById("profile-mail"),
		// nav
		linkMain: document.getElementById("link-main"),
		linkArticles: document.getElementById("link-articles"),
		linkAbout: document.getElementById("link-about"),
		linkPortfolio: document.getElementById("link-portfolio"),
	},
	index: {
		cardsHeading: document.querySelectorAll(".cards-heading"),
		cardsText: document.querySelectorAll(".cards-text"),
		layoutsHeading: document.querySelectorAll(".layouts-heading"),
		layoutsText: document.querySelectorAll(".layouts-text"),
		cyberbiologyHeading: document.querySelectorAll(".cyberbiology-heading"),
		cyberbiologyText: document.querySelectorAll(".cyberbiology-text"),
		tuskHeading: document.querySelectorAll(".tusk-heading"),
		tuskText: document.querySelectorAll(".tusk-text"),
		stonksText: document.querySelectorAll(".stonks-text"),
		readMore: document.querySelectorAll(".read"),
	},
	articles: {
		topics: document.querySelectorAll(".article__topic"),
		blockUniverseHeading: document.getElementById("block-universe-heading"),
		blockUniverse: document.getElementById("block-universe"),
		consciousAnimalsHeading: document.getElementById("conscious-animals-heading"),
		consciousAnimals: document.getElementById("conscious-animals"),
		inspirationHeading: document.getElementById("inspiration-heading"),
		inspirationText: document.getElementById("inspiration"),
		infoUniverseHeading: document.getElementById("information-universe-heading"),
		infoUniverseText: document.getElementById("information-universe"),
		programmingHeading: document.getElementById("programming-heading"),
		programmingText: document.getElementById("programming"),
		consciousnessOntologyHeading: document.getElementById("consciousness-ontology-heading"),
		consciousnessOntologyText: document.getElementById("consciousness-ontology"),
	},
	portfolio: {
		cardsHeading: document.querySelectorAll(".cards-heading"),
		cardsText: document.querySelectorAll(".cards-text"),
		layoutsHeading: document.querySelectorAll(".layouts-heading"),
		layoutsText: document.querySelectorAll(".layouts-text"),
		cyberbiologyHeading: document.querySelectorAll(".cyberbiology-heading"),
		cyberbiologyText: document.querySelectorAll(".cyberbiology-text"),
		cyberbiologyDescription: document.getElementById("cyberbiology-description"),
		tuskHeading: document.querySelectorAll(".tusk-heading"),
		tuskText: document.querySelectorAll(".tusk-text"),
		stonksText: document.querySelectorAll(".stonks-text"),
	}
};